servtest_proj/servtest/config/routes.rb
Rails.application.routes.draw do

  resources :pwm
  resources :realtime
  resources :readings

  resources :users

end

servtest_proj/servtest/app/models/pwm.rb
class Pwm < ActiveRecord::Base

end

servtest_proj/servtest/app/models/reading.rb
class Reading < ActiveRecord::Base
end

servtest_proj/servtest/app/models/real_var.rb
class RealVar < ActiveRecord::Base
end

servtest_proj/servtest/app/models/user.rb
class User < ActiveRecord::Base
end

servtest_proj/servtest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

servtest_proj/servtest/app/controllers/pwm_controller.rb
class PwmController < ApplicationController
  skip_before_filter :verify_authenticity_token


  def create
    @pwm=Pwm.first
    @pwm.update_attributes(pwm_temp:params[:pwm_temp], pwm_flow:params[:pwm_flow],setpoint:params[:setpoint],gain:params[:gain],integ:params[:integ],deriv:params[:deriv],openloop:params[:openloop],setpointH:params[:setpointH],gainH:params[:gainH],integH:params[:integH],derivH:params[:derivH])
    @pwm.save




  end


  def index

    @pwm=Pwm.all
    respond_to do |format|

      format.html # show.html.erb
      format.json { render :json => @pwm }
    end
  end



  def show
    @pwm=Pwm.first
   respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @pwm }
    end
  end


  def update

  end

end

servtest_proj/servtest/app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :set_reading, only: [:show, :edit, :update, :destroy]

  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.all
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
  end

  # GET /readings/new
  def new
    @reading = Reading.new
  end

  # GET /readings/1/edit
  def edit
  end

  # POST /readings
  # POST /readings.json
  def create
    @reading = Reading.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
        format.json { render :show, status: :created, location: @reading }
      else
        format.html { render :new }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to readings_url, notice: 'Reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reading_params
      params.require(:reading).permit(:flow_measure, :temperature_measure, :fan_set, :temperature_set)
    end
end

servtest_proj/servtest/app/controllers/realtime_controller.rb
class RealtimeController < ApplicationController
  skip_before_filter :verify_authenticity_token
def create
  @real_var=RealVar.first
  @real_var.update_attributes(temp:params[:temp], flow:params[:flow] ,setpoint:params[:setpoint],gain:params[:gain],ti:params[:ti],td:params[:td],flowset:params[:flowset],tempset:params[:tempset] ,setpointH:params[:setpointH]  )
  @real_var.save




end


def index
  @real_var=RealVar.all
  respond_to do |format|
    format.html # show.html.erb
    format.json { render :json => @real_var }
  end
end



def show
  @real_var=RealVar.first
  respond_to do |format|
    format.html # show.html.erb
    format.json { render :json => @real_var }
  end
  end


  def update

  end

end

servtest_proj/servtest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show



  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name,:status)
    end
end

servtest_proj/servtest/app/helpers/application_helper.rb
module ApplicationHelper
end

servtest_proj/servtest/app/helpers/pwm_helper.rb
module PwmHelper
end

servtest_proj/servtest/app/helpers/readings_helper.rb
module ReadingsHelper
end

servtest_proj/servtest/app/helpers/realtime_helper.rb
module RealtimeHelper
end

servtest_proj/servtest/app/helpers/users_helper.rb
module UsersHelper
end

servtest_proj/servtest/app/views/pwm/create.erb
<h1>pwm#show</h1>

servtest_proj/servtest/app/views/pwm/index.erb
<h1>Inputs towards PLC</h1>

<p>
  <strong>pwm_temp:</strong>
  <%=Pwm.first.pwm_temp%>
</p>


<p>
  <strong>pwm_flow:</strong>
  <%=Pwm.first.pwm_flow%>

</p>
<p>
  <strong>Setpoint:</strong>
  <%=Pwm.first.setpoint%>

</p>
<p>
  <strong>Gain:</strong>
  <%=Pwm.first.gain%>

</p>
<p>
  <strong>Integral:</strong>
  <%=Pwm.first.integ%>

</p>
<p>
  <strong>Derivitive:</strong>
  <%=Pwm.first.deriv%>

</p>
<p>
  <strong>Open/closed loop:</strong>
  <%=Pwm.first.openloop%>

</p>

</p>
<p>
  <strong>Setpoint Heater:</strong>
  <%=Pwm.first.setpointH%>

</p>
<p>
  <strong>Gain Heater:</strong>
  <%=Pwm.first.gainH%>

</p>
<p>
  <strong>Integral Heater:</strong>
  <%=Pwm.first.integH%>

</p>
<p>
  <strong>Derivitive Heater:</strong>
  <%=Pwm.first.derivH%>

</p>

<br>

servtest_proj/servtest/app/views/pwm/show.erb
<h1>pwm#show</h1>

<h1>Listing users</h1>
<p>
  <strong>temp:</strong>
  <%=Pwm.first.pwm_temp%>
</p>


<p>
  <strong>flow:</strong>
  <%=Pwm.first.pwm_flow%>

</p>
<p>
  <strong>Setpoint:</strong>
  <%=Pwm.first.setpoint%>

</p>
<p>
  <strong>Gain:</strong>
  <%=Pwm.first.gain%>

</p>
<p>
  <strong>Integral:</strong>
  <%=Pwm.first.integ%>

</p>
<p>
  <strong>Derivitive:</strong>
  <%=Pwm.first.deriv%>

</p>
<p>
  <strong>Open/closed loop:</strong>
  <%=Pwm.first.openloop%>

</p>
<br>

servtest_proj/servtest/app/views/pwm/update.erb
<h1>pwm#show</h1>

servtest_proj/servtest/app/views/readings/_form.html.erb
<%= form_for(@reading) do |f| %>
  <% if @reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% @reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flow_measure %><br>
    <%= f.text_field :flow_measure %>
  </div>
  <div class="field">
    <%= f.label :temperature_measure %><br>
    <%= f.text_field :temperature_measure %>
  </div>
  <div class="field">
    <%= f.label :fan_set %><br>
    <%= f.text_field :fan_set %>
  </div>
  <div class="field">
    <%= f.label :temperature_set %><br>
    <%= f.text_field :temperature_set %>
  </div>

    <div class="field">
      <%= f.label :Setpoint %><br>
      <%= f.text_field :setpoint %>
    </div>
    <div class="field">
      <%= f.label :Gain %><br>
      <%= f.text_field :gain %>
    </div>
    <div class="field">
      <%= f.label :Integral %><br>
      <%= f.text_field :integ %>
    </div>
    <div class="field">
      <%= f.label :Derivative %><br>
      <%= f.text_field :deriv %>
    </div>

    <div class="field">
      <%= f.label :Setpoint_Heater %><br>
      <%= f.text_field :setpointH %>
    </div>
    <div class="field">
      <%= f.label :Gain_Heater %><br>
      <%= f.text_field :gainH %>
    </div>
    <div class="field">
      <%= f.label :Integral_Heater %><br>
      <%= f.text_field :integH %>
    </div>
    <div class="field">
      <%= f.label :Derivative_Heater %><br>
      <%= f.text_field :derivH %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

servtest_proj/servtest/app/views/readings/edit.html.erb
<h1>Editing reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

servtest_proj/servtest/app/views/readings/index.html.erb
<h1>Listing readings</h1>

<table>
  <thead>
    <tr>
      <th>Flow measure</th>
      <th>Temperature measure</th>
      <th>Fan set</th>
      <th>Temperature set</th>
      <th>Date and Time</th>
      <th>Setpoint</th>
      <th>Gain</th>
      <th>Integral</th>
      <th>Derivative</th>
      <th>Setpoint Heater</th>
      <th>Gain Heater</th>
      <th>Integral Heater</th>
      <th>Derivative Heater</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @readings.each do |reading| %>
      <tr>
        <td><%= reading.flow_measure %></td>
        <td><%= reading.temperature_measure %></td>
        <td><%= reading.fan_set %></td>
        <td><%= reading.temperature_set %></td>
        <td><%= reading.created_at %></td>
        <td><%= reading.setpoint %></td>
        <td><%= reading.gain %></td>
        <td><%= reading.integ %></td>
        <td><%= reading.deriv %></td>
        <td><%= reading.setpointH %></td>
        <td><%= reading.gainH %></td>
        <td><%= reading.integH %></td>
        <td><%= reading.derivH %></td>
        <td><%= link_to 'Show', reading %></td>
        <td><%= link_to 'Edit', edit_reading_path(reading) %></td>
        <td><%= link_to 'Destroy', reading, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reading', new_reading_path %>

servtest_proj/servtest/app/views/readings/new.html.erb
<h1>New reading</h1>

<%= render 'form' %>

<%= link_to 'Back', readings_path %>

servtest_proj/servtest/app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flow measure:</strong>
  <%= @reading.flow_measure %>
</p>

<p>
  <strong>Temperature measure:</strong>
  <%= @reading.temperature_measure %>
</p>

<p>
  <strong>Fan set:</strong>
  <%= @reading.fan_set %>
</p>

<p>
  <strong>Temperature set:</strong>
  <%= @reading.temperature_set %>
</p>

<p>
  <strong>Setpoint:</strong>
  <%= @reading.setpoint %>
</p>

<p>
  <strong>Gain :</strong>
  <%= @reading.gain %>
</p>

<p>
  <strong>Integral:</strong>
  <%= @reading.integ %>
</p>

<p>
  <strong>Derivative:</strong>
  <%= @reading.deriv %>
</p>

<p>
  <strong>Setpoint Heater:</strong>
  <%= @reading.setpointH %>
</p>

<p>
  <strong>Gain Heater :</strong>
  <%= @reading.gainH %>
</p>

<p>
  <strong>Integral Heater:</strong>
  <%= @reading.integH %>
</p>

<p>
  <strong>Derivative Heater:</strong>
  <%= @reading.derivH %>
</p>


<%= link_to 'Edit', edit_reading_path(@reading) %> |
<%= link_to 'Back', readings_path %>

servtest_proj/servtest/app/views/realtime/create.erb
<h1>Realtime#show</h1>

servtest_proj/servtest/app/views/realtime/index.erb
<h1>Realtime#show</h1>

<h1>Listing users</h1>
<p>
  <strong>temp:</strong>
  <%=RealVar.first.temp%>
</p>


<p>
  <strong>flow:</strong>
  <%=RealVar.first.flow%>

</p>

<p>
  <strong>Fan setpoint:</strong>
  <%=RealVar.first.setpoint%>
</p>


<p>
  <strong>Heater setpoint:</strong>
  <%=RealVar.first.setpointH%>

</p>
<p>
  <strong>Fan:</strong>
  <%=RealVar.first.flowset%>
</p>


<p>
  <strong>Heat:</strong>
  <%=RealVar.first.tempset%>

</p>
<br>

servtest_proj/servtest/app/views/realtime/show.html.erb
<h1>Realtime#show</h1>

<h1>Listing users</h1>
<p>
  <strong>temp:</strong>
  <%=RealVar.first.temp%>
</p>


<p>
  <strong>flow:</strong>
  <%=RealVar.first.flow%>
</p>
<br>

servtest_proj/servtest/app/views/realtime/update.erb
<h1>Realtime#show</h1>