sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#contact', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match'/signup', to: 'users#new', via: 'get'

end

sample_app/app/models/user.rb
class User < ActiveRecord::Base
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def about
  end
  def contact
  end
end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app/app/helpers/users_helper.rb
module UsersHelper
end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'sample app', root_path, id: 'logo' %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to 'Home',    root_path %></li>
          <li><%= link_to 'Help',    help_path %></li>
          <li><%= link_to 'Sign in', '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
   <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

sample_app/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

sample_app/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

sample_app/app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to 'Sign up now!', signup_path, class: 'btn btn-large btn-primary' %>
</div>

<%= link_to image_tag('rails.png', alt: 'Rails'), 'http://rubyonrails.org/' %>

sample_app/app/views/users/new.html.erb
<%provide(:title, 'Sign up')%>

<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>